version: '3.8'

services:
  web_camera_stream:
    build: .
    container_name: web_camera_stream
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./camera_config.yml:/app/camera_config.yml
    environment:
      FLASK_ENV: development
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"